// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DetectLoops(arg1:Array<Record<string, string>>):Promise<Array<string>>;

export function ExportBackup():Promise<Record<string, any>>;

export function GetDevices():Promise<Array<Record<string, string>>>;

export function GetLocalIP():Promise<string>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSystemInfo():Promise<main.NetworkInfo>;

export function Greet(arg1:string):Promise<string>;

export function ImportBackup(arg1:Record<string, any>):Promise<void>;

export function PingMultiple(arg1:Array<string>):Promise<Array<main.PingResult>>;

export function PingSingle(arg1:string):Promise<main.PingResult>;

export function PortScan(arg1:string,arg2:Array<number>):Promise<Array<main.PortScanResult>>;

export function ResetToDefault():Promise<void>;

export function SaveSettings(arg1:Record<string, string>):Promise<void>;

export function ScanNetwork(arg1:string):Promise<Array<Record<string, string>>>;

export function StartMockScan(arg1:string):Promise<void>;

export function Traceroute(arg1:string):Promise<Array<main.TracerouteHop>>;
