// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectLoops(arg1) {
  return window['go']['main']['App']['DetectLoops'](arg1);
}

export function ExportBackup() {
  return window['go']['main']['App']['ExportBackup']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportBackup(arg1) {
  return window['go']['main']['App']['ImportBackup'](arg1);
}

export function PingMultiple(arg1) {
  return window['go']['main']['App']['PingMultiple'](arg1);
}

export function PingSingle(arg1) {
  return window['go']['main']['App']['PingSingle'](arg1);
}

export function PortScan(arg1, arg2) {
  return window['go']['main']['App']['PortScan'](arg1, arg2);
}

export function ResetToDefault() {
  return window['go']['main']['App']['ResetToDefault']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanNetwork(arg1) {
  return window['go']['main']['App']['ScanNetwork'](arg1);
}

export function StartMockScan(arg1) {
  return window['go']['main']['App']['StartMockScan'](arg1);
}

export function Traceroute(arg1) {
  return window['go']['main']['App']['Traceroute'](arg1);
}
